package generate

import (
	"os"
	"path/filepath"
	"testing"
)

func TestGenerate_SfxDirectory(t *testing.T) {
	dir := t.TempDir()

	sfxDir := filepath.Join(dir, "sfx_play")
	if err := os.Mkdir(sfxDir, 0o755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, sfxDir, "die.wav")
	writeFile(t, sfxDir, "move.wav")

	if err := Generate(dir, "github.com/hoani/mygame"); err != nil {
		t.Fatal(err)
	}

	got := readGenerated(t, sfxDir)

	want := `// Code generated by sndit; DO NOT EDIT.
package sfx_play

import (
	_ "embed"
	"github.com/hoani/sndit"
)

//go:embed "die.wav"
var die_wav []byte

//go:embed "move.wav"
var move_wav []byte

type Sound int

const (
	Die Sound = iota
	Move
)

var engine *sndit.SfxEngine[Sound]

func Init(ctx sndit.Context) {
	engine = sndit.NewSfx[Sound](ctx)
	engine.Register(Die, die_wav)
	engine.Register(Move, move_wav)
}

func Play(id Sound) {
	engine.Play(id)
}
`

	if got != want {
		t.Errorf("generated output mismatch.\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestGenerate_MusDirectory(t *testing.T) {
	dir := t.TempDir()

	musDir := filepath.Join(dir, "mus_theme")
	if err := os.Mkdir(musDir, 0o755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, musDir, "title.wav")
	writeFile(t, musDir, "gameplay.wav")

	if err := Generate(dir, "github.com/hoani/mygame"); err != nil {
		t.Fatal(err)
	}

	got := readGenerated(t, musDir)

	want := `// Code generated by sndit; DO NOT EDIT.
package mus_theme

import (
	_ "embed"
	"github.com/hoani/sndit"
)

//go:embed "gameplay.wav"
var gameplay_wav []byte

//go:embed "title.wav"
var title_wav []byte

type Sound int

const (
	Gameplay Sound = iota
	Title
)

var engine *sndit.MusicEngine[Sound]

func Init(ctx sndit.Context) {
	engine = sndit.NewMusic[Sound](ctx)
	engine.Register(Gameplay, gameplay_wav)
	engine.Register(Title, title_wav)
}

func Play(id Sound) {
	engine.Play(id)
}

func Stop() {
	engine.Stop()
}
`

	if got != want {
		t.Errorf("generated output mismatch.\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestGenerate_SkipsEmptyDirectories(t *testing.T) {
	dir := t.TempDir()

	sfxDir := filepath.Join(dir, "sfx_empty")
	if err := os.Mkdir(sfxDir, 0o755); err != nil {
		t.Fatal(err)
	}

	if err := Generate(dir, "github.com/hoani/mygame"); err != nil {
		t.Fatal(err)
	}

	genPath := filepath.Join(sfxDir, "sounds_gen.go")
	if _, err := os.Stat(genPath); !os.IsNotExist(err) {
		t.Error("expected no generated file for empty directory")
	}
}

func TestGenerate_SkipsNonMatchingDirectories(t *testing.T) {
	dir := t.TempDir()

	otherDir := filepath.Join(dir, "other")
	if err := os.Mkdir(otherDir, 0o755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, otherDir, "sound.wav")

	if err := Generate(dir, "github.com/hoani/mygame"); err != nil {
		t.Fatal(err)
	}

	genPath := filepath.Join(otherDir, "sounds_gen.go")
	if _, err := os.Stat(genPath); !os.IsNotExist(err) {
		t.Error("expected no generated file for non-matching directory")
	}
}

func TestGenerate_MultipleDirectories(t *testing.T) {
	dir := t.TempDir()

	sfxDir := filepath.Join(dir, "sfx_play")
	musDir := filepath.Join(dir, "mus_bg")
	if err := os.Mkdir(sfxDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Mkdir(musDir, 0o755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, sfxDir, "click.wav")
	writeFile(t, musDir, "loop.wav")

	if err := Generate(dir, "github.com/hoani/mygame"); err != nil {
		t.Fatal(err)
	}

	// Both should have generated files.
	if _, err := os.Stat(filepath.Join(sfxDir, "sounds_gen.go")); err != nil {
		t.Error("expected generated file in sfx_play")
	}
	if _, err := os.Stat(filepath.Join(musDir, "sounds_gen.go")); err != nil {
		t.Error("expected generated file in mus_bg")
	}
}

func TestGenerate_SkipsNonWavFiles(t *testing.T) {
	dir := t.TempDir()

	sfxDir := filepath.Join(dir, "sfx_play")
	if err := os.Mkdir(sfxDir, 0o755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, sfxDir, "click.wav")
	writeFile(t, sfxDir, "readme.txt")

	if err := Generate(dir, "github.com/hoani/mygame"); err != nil {
		t.Fatal(err)
	}

	got := readGenerated(t, sfxDir)

	// Should only include click.wav, not readme.txt.
	want := `// Code generated by sndit; DO NOT EDIT.
package sfx_play

import (
	_ "embed"
	"github.com/hoani/sndit"
)

//go:embed "click.wav"
var click_wav []byte

type Sound int

const (
	Click Sound = iota
)

var engine *sndit.SfxEngine[Sound]

func Init(ctx sndit.Context) {
	engine = sndit.NewSfx[Sound](ctx)
	engine.Register(Click, click_wav)
}

func Play(id Sound) {
	engine.Play(id)
}
`

	if got != want {
		t.Errorf("generated output mismatch.\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func writeFile(t *testing.T, dir, name string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte("fake"), 0o644); err != nil {
		t.Fatal(err)
	}
}

func readGenerated(t *testing.T, dir string) string {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(dir, "sounds_gen.go"))
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}
